service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_storage:
    backends:
      local_traces:
        memory:
          max_traces: 100000
  jaeger_query:
    storage:
      traces: local_traces
    http:
      endpoint: "${env:JAEGER_LISTEN_HOST:-127.0.0.1}:16686"
  healthcheckv2:
    use_v2: true
    http:
      endpoint: "${env:JAEGER_LISTEN_HOST:-127.0.0.1}:13133"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "${env:JAEGER_LISTEN_HOST:-127.0.0.1}:4317"
      http:
        endpoint: "${env:JAEGER_LISTEN_HOST:-127.0.0.1}:4318"

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024

exporters:
  jaeger_storage_exporter:
    trace_storage: local_traces
